name    'echoes-strongswan'
version '0.1.0'
source 'UNKNOWN'
author 'ECHOES Technologies <contact@echoes-tech.com>'
license 'Apache License, Version 2.0'
summary 'StrongSwan Module'
description 'Installs StrongSwan and configure one IPsec tunnel with a shared pass'
project_page 'https://github.com/echoes-tech/puppet-strongswan'
dependency 'puppetlabs/stdlib', '>= 0.1.6'
dependency 'puppetlabs/firewall', '>= 0.5.0'
